cache:
  paths:
  - node_modules/

services:
  - docker:dind

stages:
  - build-backend
  - build-frontend

build-backend:
  image: docker:latest
  stage: build-backend
  script:
    - apk add --no-cache curl jq python py-pip docker
    - pip install awscli
    - $(aws ecr get-login --no-include-email --region us-west-2)
    - docker build -t $REPOSITORY_URL_PROD:backend ./backend
    - docker push $REPOSITORY_URL_PROD:backend
  only:
    refs:
      - master
build-frontend:
  image: docker:latest
  stage: build-frontend
  script:
    - apk add --no-cache curl jq python py-pip docker
    - pip install awscli
    - $(aws ecr get-login --no-include-email --region us-west-2)
    - docker build -t $REPOSITORY_URL_PROD:frontend ./frontend
    - docker push $REPOSITORY_URL_PROD:frontend
  only:
    refs:
      - master
