cache:
  paths:
  - node_modules/

services:
  - docker:dind

stages:
  - build-backend
  - build-frontend
  - deploy-prod
  - deploy-staging

build-backend:
  image: docker:latest
  stage: build-backend
  script:
    - apk add --no-cache curl jq python py-pip docker
    - pip install awscli
    - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
    - docker build -t $REPOSITORY_URL:backend ./backend
    - docker push $REPOSITORY_URL:backend
  only:
    refs:
      - master
build-frontend:
  image: docker:latest
  stage: build-frontend
  script:
    - apk add --no-cache curl jq python py-pip docker
    - pip install awscli
    - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
    - docker build -t $REPOSITORY_URL:frontend ./frontend
    - docker push $REPOSITORY_URL:frontend
  only:
    refs:
      - master
deploy-prod:
  stage: deploy-prod
  image: docker:latest
  script:
    - source scripts/deploy_prod.sh
  when: manual
deploy-staging:
  stage: deploy-staging
  image: docker:latest
  script:
    - source scripts/deploy_staging.sh