cache:
  paths:
  - node_modules/

stages:
  - test
  - build

test:
  image: node:10-alpine
  stage: test
  script:
    - npm install
  only:
    refs:
      - master
build:
  image: docker:latest
  stage: build
  script:
    - apk add --no-cache curl jq python py-pip docker
    - pip install awscli
    - $(aws ecr get-login --no-include-email --region us-west-2)
    - docker build -t $REPOSITORY_URL .
    - docker push $REPOSITORY_URL
  only:
    refs:
      - master
