cache:
  paths:
  - node_modules/

services:
  - docker:dind

stages:
  - build-nodejs
  - build-angularjs

build-nodejs:
  image: docker:latest
  stage: build-nodejs
  script:
    - apk add --no-cache curl jq python py-pip docker
    - pip install awscli
    - $(aws ecr get-login --no-include-email --region us-west-2)
    - docker build -t $REPOSITORY_URL/backend-prod ./backend
    - docker push $REPOSITORY_URL
  only:
    refs:
      - master

build-angularjs:
  image: docker:latest
  stage: build-angularjs
  script:
    - apk add --no-cache curl jq python py-pip docker
    - pip install awscli
    - $(aws ecr get-login --no-include-email --region us-west-2)
    - docker build -t $REPOSITORY_URL/frontend-prod ./frontend
    - docker push $REPOSITORY_URL
  only:
    refs:
      - master
