image: node:10-alpine

variables:
  REPOSITORY_URL: 485876055632.dkr.ecr.us-west-2.amazonaws.com/csun-saps-prod

cache:
  paths:
  - node_modules/

before_script:
  - apk add --no-cache curl jq python py-pip
  - pip install awscli

stages:
  - test
  - build

test_async:
  stage: test
  script:
    - npm install
  only:
    refs:
      - master
build_image:
  stage: build
  script:
    - $(aws ecr get-login --no-include-email --region us-west-2)
    - docker build -t $REPOSITORY_URL .
    - docker push $REPOSITORY_URL
  only:
    refs:
      - master
  tags:
    - docker
