version: '3.3'

services:
    backend:
        build:
            context: ./backend
        ports:
                - "3000:3000"
        depends_on:
            - mysql
        networks:
            - docker_network
        volumes:
            - ./backend:/usr/src/app
            - /usr/src/app/node_modules
        command: npm run dev
    mysql:
        build:
            context: ./mysql
            args:
                - MYSQL_DATABASE=default_database
                - MYSQL_USER=default_user
                - MYSQL_PASSWORD=secret
                - MYSQL_ROOT_PASSWORD=root
        volumes:
            - ./data/mysql/:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - docker_network
    frontend:
        build:
          context: ./frontend
          dockerfile: Dockerfile-dev
        ports:
            - "4200:4200"
        networks:
            - docker_network
        volumes:
            - ./frontend:/usr/src/app
            - /usr/src/app/node_modules
networks:
    docker_network:
        driver: bridge
