version: '3.3'

services:
    node:
        build:
            context: .
        ports:
            - "3000:3000"
        depends_on:
            - mysql
        networks:
            - docker_network
        volumes:
            - .:/usr/src/app
    mysql:
        build:
            context: ./mysql
            args:
                - MYSQL_DATABASE=default_database
                - MYSQL_USER=default_user
                - MYSQL_PASSWORD=secret
                - MYSQL_ROOT_PASSWORD=root
        volumes:
            - ./data/mysql/:/var/lib/mysql
        ports:
            - "3307:3306"
        networks:
            - docker_network
networks:
    docker_network:
        driver: bridge
