---
- hosts: all
  become: true
  tasks:
      - name: Download node_explorer
        get_url:
          url: https://github.com/prometheus/node_exporter/releases/download/v0.16.0/node_exporter-0.16.0.linux-amd64.tar.gz
          dest: /home/ec2-user/node_exporter-0.16.0.linux-amd64.tar.gz

      - name: Extract tar
        unarchive:
          src: /home/ec2-user/node_exporter-0.16.0.linux-amd64.tar.gz
          dest: /home/ec2-user/

      - name: Move node_exporter
        shell: |
          mv /home/ec2-user/node_exporter-0.16.0.linux-amd64/node_exporter /usr/local/bin/

      - name: Create user and service
        shell: |
          useradd -rs /bin/false node_exporter

      - name: Move node_exporter.service
        shell: |
          mv /home/ec2-user/node_exporter.service /etc/systemd/system/node_exporter.service

      - name: Reload Prometheuse to register changes
        shell: |
          systemctl daemon-reload
          systemctl start node_exporter
          systemctl status node_exporter
          systemctl enable node_exporter
